DJANGO-TP-01/bibliotheque/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.index),
    path('ajout/',views.ajout),
    path("traitement/",views.traitement),
    path("affiche/<int:id>/",views.affiche),
    path("delete/<int:id>",views.delete),
    path("update/<int:id>",views.update),
    path("traitementupdate/<int:id>",views.traitementupdate),
    path("tous/", views.tous),
    path('ajax/load-modele/', views.load_modele, name='ajax_load_modele'),
    path('ajoutmarque/', views.ajoutmarque, name='ajoutmarque'),
    path('ajoutmodele/', views.ajoutmodele, name='ajoutmodele'),
    path('allmarque/', views.allmarque, name='allmarque'),
    path('deletemodele/<modele_id>', views.deletemodele, name='deletemodele'),
]

DJANGO-TP-01/modele/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bibliotheque.urls'))
]

DJANGO-TP-01/bibliotheque/models.py
from django.db import models


class Marque(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Modele(models.Model):
    marque = models.ForeignKey(Marque, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Voiture(models.Model):
    name = models.CharField(max_length=100)
    date_de_commande = models.DateField(null=True, blank=True)
    marque = models.ForeignKey(Marque, on_delete=models.SET_NULL, null=True)
    modele = models.ForeignKey(Modele, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name 

    def dico(self):
        return {"marque" : self.marque, "modele" : self.modele, "date_de_commande" : self.date_de_commande}
        

DJANGO-TP-01/bibliotheque/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from . import models
from django import forms
from .models import Voiture, Modele, Marque


class VoitureForm(forms.ModelForm):
    class Meta:
        model = Voiture
        fields = ('name', 'date_de_commande', 'marque','modele')
        labels = {"modele":"Modèle", "name":"Votre nom :", "date_de_commande":"Date de commande :"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['modele'].queryset = Modele.objects.none()

        if 'marque' in self.data:
            try:
                marque_id = int(self.data.get('marque'))
                self.fields['modele'].queryset = Modele.objects.filter(marque_id=marque_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['modele'].queryset = self.instance.marque.modele_set.order_by('name')
            
            
class AjoutForm(ModelForm):
    class Meta:
        model = Marque
        fields = ('name',)
        labels = {"name":"Nom de la marque"}

class AjoutMoForm(ModelForm):
        class Meta:
            model = Modele
            fields = ('marque', 'name',)
            labels = {"name":"Nom du modèle"}

DJANGO-TP-01/bibliotheque/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import VoitureForm
from .forms import AjoutForm
from .forms import AjoutMoForm
from . import  models
from django import forms
from bibliotheque.models import Voiture
from django.urls import reverse_lazy
from .models import Voiture, Modele, Marque


def ajout(request):
    marque_id = request.GET.get('marque')
    modele = Modele.objects.filter(marque_id=marque_id).order_by('name')
    if request.method == "POST":
        form = VoitureForm(request)
        if form.is_valid():
            voiture = form.save()
            return HttpResponseRedirect("/")
        else:
            return render(request,"ajout.html",{"form": form, 'modele': modele})
    else :
        form = VoitureForm()
        return render(request,"ajout.html",{"form" : form, 'modele': modele})


def traitement(request):
    lform = VoitureForm(request.POST)
    if lform.is_valid():
        voiture = lform.save()
        return HttpResponseRedirect("../tous")
    else:
        return render(request,"ajout.html",{"form": lform})


def index(request):
    liste = list(models.Voiture.objects.all())
    return render(request, 'index.html', {'liste': liste})


def affiche(request, id):
    voiture = models.Voiture.objects.get(pk=id)
    return render(request,"affiche.html",{"voiture" : voiture})


def delete(request, id):
    voiture = models.Voiture.objects.get(pk=id)
    voiture.delete()
    return HttpResponseRedirect("../tous")


def update(request, id):
    marque_id = request.GET.get('marque')
    modele = Modele.objects.filter(marque_id=marque_id).order_by('name')
    voiture = models.Voiture.objects.get(pk=id)
    lform = VoitureForm(voiture.dico())
    return render(request, "update.html", {"form": lform,"id":id,'modele': modele})


def traitementupdate(request, id):
    lform = VoitureForm(request.POST)
    if lform.is_valid():
        voiture = lform.save(commit=False)
        voiture.id = id;
        voiture.save()
        return HttpResponseRedirect("../tous")
    else:
        return render(request, "update.html", {"form": lform, "id": id})


def tous(request):
    voiture = list(models.Voiture.objects.all())
    marque = list(models.Marque.objects.all())
    modele = list(models.Modele.objects.all())
    return render(request, 'tous.html', {'voiture': voiture, 'marque': marque, 'modele': modele})


def load_modele(request):
    marque_id = request.GET.get('marque')
    modele = Modele.objects.filter(marque_id=marque_id).order_by('name')
    return render(request, 'modele_options.html', {'modele': modele})
    
def ajoutmarque(request):
    submitted = False
    if request.method == "POST":
        form = AjoutForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/ajout")
    else: 
        form = AjoutForm
        if 'submitted' in request.GET:
            submitted = True
    
    return render(request, 'ajoutmarque.html', {'form': form})
    
def ajoutmodele(request):
    submitted = False
    if request.method == "POST":
        form = AjoutMoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/ajout")
    else: 
        form = AjoutMoForm
        if 'submitted' in request.GET:
            submitted = True
    
    return render(request, 'ajoutmodele.html', {'form': form})
    

def allmarque(request):
    voiture = list(models.Voiture.objects.all())
    marque = models.Marque.objects.all()
    modele = models.Modele.objects.all()
    return render(request, 'allmarque.html', {'marque': marque, 'modele': modele, 'voiture': voiture})

def deletemodele(request, modele_id):
    modele = models.Modele.objects.get(pk=modele_id)
    modele.delete()
    return HttpResponseRedirect("../allmarque")

DJANGO-TP-01/bibliotheque/templates/affiche.html
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/affiche.css' %}"
  />
  <title>{% block title %} fiche {{voiture.modele}}{% endblock %}</title>
</head>
<nav>
  <h1>Mon site de commande de voitures</h1>
  <div class="onglets">
    <p class="link"><a href="../../">Accueil</a></p>
    <p class="link"><a href="../../ajout/">Commander une voiture</a></p>
    <p class="link"><a class="linka" href="#">Les voitures commandées</a></p>
    <p class="link"><a href="../../allmarque/">La base de données</a></p>
    <form>
      <input type="search" placeholder="Rechercher" />
    </form>
  </div>
</nav>
<div class="fiche">
  <h1>Commande d'une {{voiture.modele}}</h1>
  <p>
    {{voiture.name}} a commandé le {{voiture.date_de_commande}} une
    {{voiture.marque}} {{voiture.modele}}
  </p>
  <div class="bouton">
    <a href="../../tous">
      <button type="button" class="btn btn-secondary">Retour</button>
    </a>
  </div>
</div>
{% endblock %}

DJANGO-TP-01/bibliotheque/templates/ajout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/ajout.css' %}">
    <title>{% block title %}Commander une voiture{% endblock %}</title>
</head>
    <nav>
        <h1>Mon site de commande de voitures</h1>
        <div class="onglets">
            <p class="link"><a href="../">Accueil</a></p>
            <p class="link"><a class="linka" href="#">Commander une voiture</a></p>
            <p class="link"><a href="../tous">Les voitures commandées</a></p>
            <p class="link"><a href="../allmarque/">La base de données</a></p>
            <form>
                <input type="search" placeholder="Rechercher">
            </form>
        </div>
    </nav>
    <div class="letout">
      <form class="quest" method="post" action="/traitement/">
          {% csrf_token %}
        <div class="form-row">
          <div class="form-group">
            {{form.name|as_crispy_field}}
            <div id="emailHelp" class="form-text">Votre nom et prénom</div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group">
            {{form.date_de_commande|as_crispy_field}}
            <div id="emailHelp" class="form-text">Sous la forme AAAA-MM-JJ</div>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-6">
            {{form.marque|as_crispy_field}}
            <div id="emailHelp" class="form-text">Vous ne trouvez pas votre marque ? Ajoutez la <a href="{% url 'ajoutmarque' %}">depuis ce lien</a></div>
          </div>
          <div class="form-group col-sm-6">
            {{form.modele|as_crispy_field}}
            <div id="emailHelp" class="form-text">Vous ne trouvez pas votre modèle ? Ajoutez le <a href="{% url 'ajoutmodele' %}">depuis ce lien</a></div>
          </div>
        </div>
        <div class="buttton">
          <input id="butt" class=" btn btn-primary" type="submit" value="Envoyer les données"\>
        </div>
      </form>
      <div class="button">
      <form method="post" id="VoitureForm" data-modele-url="{% url 'ajax_load_modele' %}" novalidate>
        <a class="btn btn-secondary"href="/">Retour</a>
      </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_marque").change(function () {
      var url = $("#VoitureForm").attr("data-modele-url");  
      var marqueId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'marque': marqueId       
        },
        success: function (data) {  
          $("#id_modele").html(data);  
        }
      });
    });
  </script>
{% endblock %}

DJANGO-TP-01/bibliotheque/templates/ajoutmarque.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/ajoutmodele.css' %}">
	<title>{% block title %}Ajouter une marque à la base de données{% endblock %}</title>
</head>
	<nav>
		<h1>Mon site de commande de voitures</h1>
		<div class="onglets">
			<p class="link"><a href="../">Accueil</a></p>
			<p class="link"><a class="linka" href="#">Commander une voiture</a></p>
			<p class="link"><a href="../tous">Les voitures commandées</a></p>
			<p class="link"><a href="../allmarque/">La base de données</a></p>
			<form>
				<input type="search" placeholder="Rechercher">
			</form>
		</div>
	</nav>
		<form action="" method=POST>
			{% csrf_token %}
			
				<div class="row">
			  	<div class="form-group">
					{{form.name|as_crispy_field}}
					<div id="emailHelp" class="form-text">Ajoutez la marque que vous désirez faire apparaître dans la base de données</div>
			  	</div>
				</div>
				<div class="boutonsub">
					<input class=" btn btn-primary" type="submit" name="" value="Suivant">
				</div>
		
		</div>
		</form>
{% endblock %}
	
	

DJANGO-TP-01/bibliotheque/templates/ajoutmodele.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/ajoutmodele.css' %}">
	<title>{% block title %}Ajouter un modèle à la base de données{% endblock %}</title>
</head>
	<nav>
		<h1>Mon site de commande de voitures</h1>
		<div class="onglets">
			<p class="link"><a href="../">Accueil</a></p>
			<p class="link"><a class="linka" href="#">Commander une voiture</a></p>
			<p class="link"><a href="../tous">Les voitures commandées</a></p>
			<p class="link"><a href="../allmarque/">La base de données</a></p>
			<form>
				<input type="search" placeholder="Rechercher">
			</form>
		</div>
	</nav>
		<form action="" method=POST>
			{% csrf_token %}
			<div class="form1">
				<div class="form2">
					<div class="row">
			  		<div class="form-group col-sm-5">
						{{form.marque|as_crispy_field}}
						<div id="emailHelp" class="form-text">Sélectionnez la marque à laquelle vous voulez ajouter le modèle.</div>
			  		</div>
			  		<div class="form-group col-sm-5">
						{{form.name|as_crispy_field}}
						<div id="emailHelp" class="form-text">Ajoutez le modèle que vous voulez</div>
			  		</div>
					</div>
				</div>
				<div class="boutonsub">
					<input class=" btn btn-primary" type="submit" name="" value="Suivant">
				</div>
			</div>
		</form>
{% endblock %}

DJANGO-TP-01/bibliotheque/templates/allmarque.html
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/allmarquee.css' %}"
  />
  <title>{% block title %}Toute la base de données{% endblock %}</title>
</head>
<nav>
  <h1>Mon site de commande de voitures</h1>
  <div class="onglets">
    <p class="link"><a href="../">Accueil</a></p>
    <p class="link"><a href="../ajout">Commander une voiture</a></p>
    <p class="link"><a href="../tous">Les voitures commandées</a></p>
    <p class="link"><a class="linka" href="#">La base de données</a></p>
    <form>
      <input type="search" placeholder="Rechercher" />
    </form>
  </div>
</nav>
<div class="alltout">
  <table class="table table-light table-striped table-bordered table-sm">
    <thead>
      <tr>
        <th scope="col">Marque</th>
        <th scope="col">Modèle</th>
      </tr>
    </thead>
    <tbody>
      {% for modele in modele %}
      <tr>
        <td>{{modele.marque}}</td>
        <td>
          <div class="dis">
            <p>{{modele}}</p>
            <a
              href="{% url 'deletemodele' modele.id %}"
              class="btn btn-outline-danger"
              >Supprimer</a
            >
          </div>
        </td>
      </tr>
      {% endfor %}
      <td><a href="{% url 'ajoutmarque' %}">Ajouter une marque</a></td>
      <td><a href="{% url 'ajoutmodele' %}">Ajouter un modèle</a></td>
    </tbody>
  </table>
</div>

{% endblock %}

DJANGO-TP-01/bibliotheque/templates/base.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %} {% endblock %}
    <footer class="footer-distributed">
      <div class="footer-right">
        <a href="pas-encore-haha"><i class="fa fa-facebook"></i></a>
        <a href="pas-encore-haha"><i class="fa fa-instagram"></i></a>
        <a href="https://www.linkedin.com/in/martin-baumgaertner-b17601221/"
          ><i class="fa fa-linkedin"></i
        ></a>
        <a href="https://github.com/martinbaumg"
          ><i class="fa fa-github"></i
        ></a>
      </div>
      <div class="footer-left">
        <p class="footer-links">
          <a class="link-1" href="#">Accueil</a>
          <a href="#">Blog</a>
          <a href="#">Autre</a>
          <a href="#">A propos</a>
          <a href="#">Contact</a>
        </p>
        <p>Martin Baumgaertner &copy; 2022</p>
      </div>
    </footer>
  </body>
</html>

DJANGO-TP-01/bibliotheque/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block title %}Bienvenue sur l'accueil du site{% endblock %}</title>
</head>
    <nav>
        <h1>Mon site de commande de voitures</h1>
        <div class="onglets">
            <p class="link"><a class="linka" href="#">Accueil</a></p>
            <p class="link"><a href="ajout/">Commander une voiture</a></p>
            <p class="link"><a href="tous/">Les voitures commandées</a></p>
            <p class="link"><a href="allmarque/">La base de données</a></p>
            <form>
                <input type="search" placeholder="Rechercher">
            </form>
        </div>
    </nav>
    <div class="fakebody">
        <a href="ajout/" class="shiny-btn">Commander une voiture</a>
    </div>
{% endblock %}

DJANGO-TP-01/bibliotheque/templates/livre.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/livreee.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Tous les livres</title>
</head>
<body>
    <nav>
        <h1>Mon site de voitures personnalisées</h1>
        <div class="onglets">
            <p class="link"><a href="../">Accueil</a></p>
            <p class="link"><a href="../ajout/">Ajouter une voiture</a></p>
            <p class="link"><a class="linka" href="#">Toutes les voitures</a></p>
            <form>
                <input type="search" placeholder="Rechercher">
            </form>
        </div>
    </nav>
    <div class="test">
       
        <div class="les-livres">
            {% for l in voiture %}
                <li>
                    <section class="part1">
                        <span></span>
                        <section class="sous-partie">
                            <p>
                            {{l.marque}} {{l.modele}}, date de production : {{l.date_production}}
                                <div class="details">
                                    <a href="../affiche/{{l.id}}">afficher les détails</a>
                                    <a href="../delete/{{l.id}}">effacer</a>
                                    <a href="../update/{{l.id}}">effectuer une mise à jour</a>
                                </div>
                            </p>
                    </section>
                </li>
            {%endfor%}
        </div> 
    </div>
    <footer class="footer-distributed">
        <div class="footer-right">
          <a href="pas-encore-haha"><i class="fa fa-facebook"></i></a>
          <a href="pas-encore-haha"><i class="fa fa-instagram"></i></a>
          <a href="https://www.linkedin.com/in/martin-baumgaertner-b17601221/"><i class="fa fa-linkedin"></i></a>
          <a href="https://github.com/martinbaumg"><i class="fa fa-github"></i></a>
        </div>
        <div class="footer-left">
          <p class="footer-links">
            <a class="link-1" href="#">Accueil</a>
            <a href="#">Blog</a>
            <a href="#">Autre</a>
            <a href="#">A propos</a>
            <a href="#">test</a>
          </p>
          <p>Martin Baumgaertner &copy; 2022</p>
        </div>
      </footer>
</body>
</html>

DJANGO-TP-01/bibliotheque/templates/merci.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Commander une voiture</title>
  </head>
  <body>
    ok c bon merci c enreigs
  </body>
</html>

DJANGO-TP-01/bibliotheque/templates/modele_options.html
<option value="">---------</option>
{% for modele in modele %}
<option value="{{ modele.pk }}">{{ modele.name }}</option>
{% endfor %}

DJANGO-TP-01/bibliotheque/templates/tous.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/touss.css' %}">
    <title>{% block title %}Tous les voitures commandées{% endblock %}</title>
</head>
<body>
    <nav>
        <h1>Mon site de commande de voitures</h1>
        <div class="onglets">
            <p class="link"><a href="../">Accueil</a></p>
            <p class="link"><a href="../ajout/">Commander une voiture</a></p>
            <p class="link"><a class="linka" href="#">Les voitures commandées</a></p>
            <p class="link"><a href="../allmarque">La base de données</a></p>
            <form>
                <input type="search" placeholder="Rechercher">
            </form>
        </div>
    </nav>
   <div><br><br><br></div>
    <div class="test">
        <div class="les-livres">
            {% for l in voiture %}
                <li>
                    <section class="part1">
                        <span></span>
                        <section class="sous-partie">
                            <p>
                            {{l.marque}} {{l.modele}}, commandé par {{l.name}}
                                <div class="details">
                                    <a href="../affiche/{{l.id}}">afficher détails</a>
                                    <a href="../delete/{{l.id}}">supprimer</a>
                                    <a href="../update/{{l.id}}">mettre à jour</a>
                                </div>
                            </p>
                    </section>
                </li>
            {%endfor%}
        </div> 
    </div>
<div><br><br><br></div>

{% endblock %}

DJANGO-TP-01/bibliotheque/templates/update.html
{% extends 'base.html' %} 
{% load static %} {% load crispy_forms_tags %} 
{% block content %}
<head>
  <title>{% block title %}Modifications{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/ajout.css' %}" />
</head>
<nav>
  <h1>Mon site de commande de voitures</h1>
  <div class="onglets">
    <p class="link"><a href="../">Accueil</a></p>
    <p class="link"><a href="../ajout">Commander une voiture</a></p>
    <p class="link">
      <a class="linka" href="../tous">Les voitures commandées</a>
    </p>
    <p class="link"><a href="../allmarque/">La base de données</a></p>
    <form>
      <input type="search" placeholder="Rechercher" />
    </form>
  </div>
</nav>
<div class="letout">
  <form class="quest" method="post" action="/traitementupdate/{{id}}">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group">
        {{form.name|as_crispy_field}}
        <div id="emailHelp" class="form-text">Votre nom et prénom</div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group">
        {{form.date_de_commande|as_crispy_field}}
        <div id="emailHelp" class="form-text">Sous la forme AAAA-MM-JJ</div>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-sm-6">
        {{form.marque|as_crispy_field}}
        <div id="emailHelp" class="form-text">
          Vous ne trouvez pas votre marque ? Ajoutez la
          <a href="{% url 'ajoutmarque' %}">depuis ce lien</a>
        </div>
      </div>
      <div class="form-group col-sm-6">
        {{form.modele|as_crispy_field}}
        <div id="emailHelp" class="form-text">
          Vous ne trouvez pas votre modèle ? Ajoutez le
          <a href="{% url 'ajoutmodele' %}">depuis ce lien</a>
        </div>
      </div>
    </div>
    <div class="buttton">
      <input
        id="butt"
        class="btn btn-primary"
        type="submit"
        value="Envoyer les données"
        \
      />
    </div>
  </form>
  <div class="button">
    <form
      method="post"
      id="VoitureForm"
      data-modele-url="{% url 'ajax_load_modele' %}"
      novalidate
    >
      <a class="btn btn-secondary" href="/">Retour</a>
    </form>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_marque").change(function () {
    var url = $("#VoitureForm").attr("data-modele-url");
    var marqueId = $(this).val();

    $.ajax({
      url: url,
      data: {
        marque: marqueId,
      },
      success: function (data) {
        $("#id_modele").html(data);
      },
    });
  });
</script>
{% endblock %}